
CXX = g++


CXXFLAGS = -Wall -std=c++11


all: proj5copy proj5heap

proj5copy: proj5copy.cc
    $(CXX) $(CXXFLAGS) -o proj5copy proj5copy.cc

proj5heap: proj5heap.cc
    $(CXX) $(CXXFLAGS) -o proj5heap proj5heap.cc

clean:
    rm -f proj5copy proj5heap
